name: discogs_api_client_example
description: "A Dart/Flutter client to interact with Discogs API to access artists, labels, masters, releases, and search. Does not provide any methods that need user level authentication."
version: 0.0.0
homepage: https://github.com/akashskypatel/discogs_api_client

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  discogs_api_client:
    path: ..
  
flutter:
  assets:
    - .env