name: discogs_api_client
description: "A Dart/Flutter client to interact with Discogs API to access artists, labels, masters, releases, and search. Does not provide any methods that need user level authentication."
version: 0.2.0
homepage: https://github.com/akashskypatel/discogs_api_client

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  fuzzy: ^0.5.1
  http: ^1.3.0
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

#flutter:
#  assets:
#    - .env
