name: discogs_api_client
description: "A Dart/Flutter client for interacting with the Discogs API."
version: 0.1.0
homepage: https://github.com/akashskypatel/discogs_api_client

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  fuzzy: ^0.5.1
  http: ^1.3.0
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5

flutter:
  assets:
    - .env